version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: ["enhancement", "github_actions", "k::dependencies", "k::toolchain"]
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    labels: ["enhancement", "npm", "k::dependencies", "k::toolchain"]
    schedule:
      interval: daily
